### ISSUE TITLE
it seems agent can not run on a multi-nic host

### ISSUE THREAD

**Issue by BenjaminHuang** [xiaods/k8e#206]
I have two nic on the test host:
enp0s3: 10.0.2.15/24
enp0s8: 192.168.56.120/24

I tried to run agent with:
/usr/local/bin/k8e agent https://192.168.56.110:6443 --token K102282e8743efba6e793988302f2107a641f79da6b9285fe215cfb98afe1571d10::server:3166a4a1cc3e24eef430b1ada21e684d --node-ip 192.168.56.120 --node-external-ip 192.168.56.120 --server
What I was expecting is k8e-agent can bind on enp0s8 and use 192.168.56.120 as both serving and requesting address.

However, enp0s3/10.0.2.15 is still being used internally, as the proxy address. Below is from /var/log/syslog
ERRO[2022-02-15T02:58:08.640048331Z] Failed to connect to proxy                    error="dial tcp 10.0.2.15:6443: connect: connection refused"
ERRO[2022-02-15T02:58:08.640102380Z] Remotedialer proxy error                      error="dial tcp 10.0.2.15:6443: connect: connection refused"

I remembered k3s has a --flannel-iface option to solve the similar issue，but k8e could have been tailored fannel from code base. So it may need some adaption. I'll look into the source code in my spare time.

**Comment by xiaods** [comment]
dont need 
```
--node-ip 192.168.56.120 --node-external-ip 192.168.56.120
```
