### ISSUE TITLE
有离线安装方法么，过内下载太难了

### ISSUE THREAD

**Issue by snakeliwei** [xiaods/k8e#207]

**Comment by xiaods** [comment]
感谢反馈，我马上启动gitee.com的镜像方案，方便下载，安装。

**Comment by xiaods** [comment]
https://gitee.com/xds2000/k8e/issues/I4VDEZ

**Comment by xiaods** [comment]
git clone代码后，国内机器编译需要注意，有基础可以自己编写一个安装包，欢迎协助完成：

hack/download替换：

1. https://gitee.com/xds2000/runc.git
2. https://gitee.com/xds2000/plugins.git

然后make

**Comment by xiaods** [comment]
https://gitee.com/xds2000/k8e/releases/v1.21.10+k8e1
离线下载包提供，请查收。安装包中还有安装步骤。

**Comment by snakeliwei** [comment]
收到，感谢……
