### ISSUE TITLE
最新的安装有问题Cilium会安装不上

### ISSUE THREAD

**Issue by snakeliwei** [xiaods/k8e#223]

**Comment by snakeliwei** [comment]
```
Created symlink /etc/systemd/system/multi-user.target.wants/k8e.service → /etc/systemd/system/k8e.service.
[INFO]  systemd: Starting k8e
sh: 457: [[: not found
```
安装脚本有个报错，
最后Cilium status
```
ℹ️  using Cilium version "v1.10.5"
🔮 Auto-detected IPAM mode: cluster-pool
❌ Cluster name "" is not valid, must match regular expression: ^[a-z0-9]([-a-z0-9]*[a-z0-9])$
↩️ Rolling back installation...
```

**Comment by xiaods** [comment]
> ```
> Created symlink /etc/systemd/system/multi-user.target.wants/k8e.service → /etc/systemd/system/k8e.service.
> [INFO]  systemd: Starting k8e
> sh: 457: [[: not found
> ```
> 
> 安装脚本有个报错， 最后Cilium status
> 
> ```
> ℹ️  using Cilium version "v1.10.5"
> 🔮 Auto-detected IPAM mode: cluster-pool
> ❌ Cluster name "" is not valid, must match regular expression: ^[a-z0-9]([-a-z0-9]*[a-z0-9])$
> ↩️ Rolling back installation...
> ```

已经修复了，你再次安装一遍。问题出在没有声明KUBECONFIG。当然你可以手工声明一下。
export KUBECONFIG=/etc/k8e/k8e.yaml  && cilium install

**Comment by xiaods** [comment]
```
sh: 457: [[: not found
```
see the code:
```
 -->this   if [[ ${CMD_K8E} == *"server"* ]]; then
        info 'install cilium operator and setup cilium cni'
        KUBECONFIG=/etc/${SYSTEM_NAME}/${SYSTEM_NAME}.yaml 
        $SUDO chmod 666 ${KUBECONFIG}
        cilium install
    fi
```

please do me a favor, 多测试下，我之前测试过，应该没问题的。你是在root账号下还是普通user下呢？给我一个反馈我看看。也欢迎PR帮我修一下。

**Comment by xiaods** [comment]
> 是在ubuntu这个用户下装的，之前一版没有问题的。我在试试

你帮看看，如果有问题，我在找下原因。

**Comment by xiaods** [comment]
@snakeliwei  最新的安装脚本修了，可以重新安装下。
