### ISSUE TITLE
怎么清理K8E集群

### ISSUE THREAD

**Issue by ZhangChengJi** [xiaods/k8e#225]

**Comment by snakeliwei** [comment]
+1，要是能提供重新初始化集群的功能就可以很方便的做一些测试工作了

**Comment by ZhangChengJi** [comment]
如果可以像sealos一样一键clean，那是最棒的

**Comment by xiaods** [comment]
k8e释放的所有命令都在/usr/local/bin/下。

**Comment by xiaods** [comment]
https://getk8e.com/docs/install/clean-k8e/

增加清理教程
