### ISSUE TITLE
最新版本安装第二台master节点添加不上

### ISSUE THREAD

**Issue by snakeliwei** [xiaods/k8e#231]
```
setup_env() {
    # --- use command args if passed or create default ---
    case "$1" in
        # --- if we only have flags discover if command should be server or agent ---
        (-*|"")
            if [ -z "${K8E_URL}" ]; then
                CMD_K8E=server
            else
                if [ -z "${K8E_TOKEN}" ] && [ -z "${K8E_TOKEN_FILE}" ] && [ -z "${K8E_CLUSTER_SECRET}" ]; then
                    fatal "Defaulted k8e exec command to 'agent' because K8E_URL is defined, but K8E_TOKEN, K8E_TOKEN_FILE or K8E_CLUSTER_SECRET is not defined."
                fi
                CMD_K8E=agent
            fi
        ;;
        # --- command is provided ---
        (*)
            CMD_K8E=$1
            shift
        ;;
    esac
```
应该是这段shell有点问题

**Comment by snakeliwei** [comment]
`setup_env() {
    # --- use command args if passed or create default ---
    case "$1" in
        # --- if we only have flags discover if command should be server or agent ---
        (-*|"")
            if [ -z "${K8E_URL}" ]; then
                CMD_K8E=server
            else
                if [ -z "${K8E_TOKEN}" ] && [ -z "${K8E_TOKEN_FILE}" ] && [ -z "${K8E_CLUSTER_SECRET}" ]; then
                    fatal "Defaulted k8e exec command to 'agent' because K8E_URL is defined, but K8E_TOKEN, K8E_TOKEN_FILE or K8E_CLUSTER_SECRET is not defined."
                fi
                CMD_K8E=agent
            fi
        ;;
        # --- command is provided ---
        (*)
            CMD_K8E=$1
            shift
        ;;
    esac`

**Comment by xiaods** [comment]
能否提供日志：
```
journalctl -u k8e.service > k8e.log
```

**Comment by xiaods** [comment]
一般加不上都是token不匹配。咱们看看日志信息才好判断

**Comment by xiaods** [comment]
教程更新，支持了多master的情况，请按安装文档重新安装就可以：
https://getk8e.com/docs/install/quick-start/

**Comment by xiaods** [comment]
修复
