### ISSUE TITLE
清理脚本清理的不太干净，重新安装后有部分容器信息会在集群中

### ISSUE THREAD

**Issue by snakeliwei** [xiaods/k8e#232]
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/838980/160072433-e7ea3aa6-2c12-43e0-bf06-b71c2a56dd5d.png">

**Comment by xiaods** [comment]
这块不用清理，按照k8s的设计，kubelet每1分钟就会清理不用的容器。https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images

**Comment by xiaods** [comment]
FYI
