### ISSUE TITLE
server is not ready: https://127.0.0.1:6443/v1-k8e/readyz: 500 Internal Server Error

### ISSUE THREAD

**Issue by xiaocode** [xiaods/k8e#274]
When I run k8e server,It shows this log:
"Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"

How can I solve it?

**Comment by xiaods** [comment]
> When I run k8e server,It shows this log: "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
> 
> How can I solve it?

don't worry, it have not installed cni correctly.
use 
```
cilium install 
```
to initially setup cni network

**Comment by xiaods** [comment]
@xiaocode  怎么样，搞定没

**Comment by xiaocode** [comment]
@xiaods 可以的，已经用起来了！感谢！
