### ISSUE TITLE
the cilium intalled fail on latest version

### ISSUE THREAD

**Issue by snakeliwei** [xiaods/k8e#275]
this is the k8e log

Oct 10 17:13:17 VM-0-118-ubuntu k8e[11777]: E1010 17:13:17.030292   11777 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"metrics-server-74474969b-45hmf_kube-system(6e500cfa-1ea8-4097-8c75-ca6c551810d6)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"metrics-server-74474969b-45hmf_kube-system(6e500cfa-1ea8-4097-8c75-ca6c551810d6)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"3580f149a703582240f49bfbc26ff54cf7d2e85012fda5547e632a369471a9f9\\\": plugin type=\\\"cilium-cni\\\" name=\\\"cilium\\\" failed (add): unable to connect to Cilium daemon: failed to create cilium agent client after 30.000000 seconds timeout: Get \\\"http:///var/run/cilium/cilium.sock/v1/config\\\": dial unix /var/run/cilium/cilium.sock: connect: no such file or directory\\nIs the agent running?\"" pod="kube-system/metrics-server-74474969b-45hmf" podUID=6e500cfa-1ea8-4097-8c75-ca6c551810d6

**Comment by snakeliwei** [comment]
ubuntu 22.04

**Comment by xiaods** [comment]
please found /etc/cni/net.d/05-cilium.conf and I deleted it on all nodes，systemctl restart k8e, The cluster will back to normal. have a try

**Comment by xiaods** [comment]
@snakeliwei hi buddy,

Please do me a favor to testing the cilium install works:
```
cilium uninstall

cilium install --helm-set-string=ipam.operator.clusterPoolIPv4PodCIDR="10.42.0.0/16",kubeProxyReplacement=strict

```

for my ubuntu 22.04, it works.
and k8s install.sh already update right now.

**Comment by snakeliwei** [comment]
It is work on master node , but another error occurs on work node install.  here is the cilium pod log.
```
level=info msg="Auto-disabling \"enable-bpf-clock-probe\" feature since KERNEL_HZ cannot be determined" error="Cannot probe CONFIG_HZ" subsys=daemon
level=info msg="Using autogenerated IPv4 allocation range" subsys=node v4Prefix=10.28.0.0/16
level=info msg="Initializing daemon" subsys=daemon
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=info msg="Establishing connection to apiserver" host="https://127.0.0.1:6443" subsys=k8s
level=error msg="Unable to contact k8s api-server" error="Get \"https://127.0.0.1:6443/api/v1/namespaces/kube-system\": dial tcp 127.0.0.1:6443: connect: connection refused" ipAddr="https://127.0.0.1:6443" subsys=k8s
level=fatal msg="Unable to initialize Kubernetes subsystem" error="unable to create k8s client: unable to create k8s client: Get \"https://127.0.0.1:6443/api/v1/namespaces/kube-system\": dial tcp 127.0.0.1:6443: connect: connection refused" subsys=daemon
```

It seems the the k8s api url is untouchabled..

**Comment by xiaods** [comment]
Thanks your report, k8sServiceHost is bad idea for settting, it will add more effort on our deploymnet. i will dig some way to overcome this settings pain.

**Comment by xiaods** [comment]
@snakeliwei  with many case with cilium kubeProxyReplacement=strict
I have add env API_SERVER_IP cilium cni插件需要指定api-server的IP, 必须是主机IP to install.sh

Now k8e fully support cilium ctl 1.12
