### ISSUE TITLE
cilium version in install.sh mismatch to the latest air-gap images

### ISSUE THREAD

**Issue by ethinx** [xiaods/k8e#283]
In air-gap image list of version `v1.25.3+k8e1`, it shows the cilium image tag is `v1.12.2`. But the [install.sh](https://getk8e.com/install.sh) shows cilium is installed with version `v1.12.3`.

**Comment by xiaods** [comment]
oh, I will fix it later.

**Comment by xiaods** [comment]
fixed

**Comment by xiaods** [comment]
https://github.com/xiaods/k8e/releases/tag/v1.25.3%2Bk8e2
