### ISSUE TITLE
How to change api-server IP?

### ISSUE THREAD

**Issue by xiaocode** [xiaods/k8e#289]
I change my network, it got another IP, then the k8s can not start.

**Comment by xiaods** [comment]
Oops, the failed node is master node else salve node?

**Comment by xiaods** [comment]
all k8e env is setting to this file: /etc/systemd/system/k8e.service.env,  please double check.
after you get some change, you should be restart k8e service like blow command:
```
systemctl restart k8e
```

**Comment by xiaocode** [comment]
Yeah,It is master node.I reinstall the k8s, and set the API_SERVER_IP as xxx.domain.local,then update the hosts file direct the url to IP, solved it!

**Comment by xiaocode** [comment]
> 

Next time I have a try!

**Comment by xiaods** [comment]
good news.

**Comment by xiaods** [comment]
resolved as expected.
/close
