### ISSUE TITLE
The second and third master node can not be added with latest version

### ISSUE THREAD

**Issue by snakeliwei** [xiaods/k8e#290]
`root@weiban-prod-k8e-master-02:~# systemctl status k8e -l
● k8e.service - Simple Kubernetes Distribution
     Loaded: loaded (/etc/systemd/system/k8e.service; enabled; vendor preset: enabled)
     Active: activating (start) since Wed 2022-12-21 21:24:25 CST; 5min ago
       Docs: https://getk8e.com
    Process: 2951 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 2953 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 2954 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
   Main PID: 2955 (k8e-server)
      Tasks: 37
     Memory: 398.8M
        CPU: 5min 47.471s
     CGroup: /system.slice/k8e.service
             └─2955 "/usr/local/bin/k8e server" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""

Dec 21 21:29:57 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:29:57+08:00" level=info msg="Waiting for etcd server to become available"
Dec 21 21:29:57 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:29:57+08:00" level=error msg="unable to read node password file: open /etc/k>
Dec 21 21:29:57 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:29:57+08:00" level=info msg="Waiting to retrieve agent configuration; server>
Dec 21 21:29:57 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:29:57+08:00" level=info msg="Tunnel server egress proxy waiting for runtime >
Dec 21 21:30:02 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:30:02+08:00" level=error msg="unable to read node password file: open /etc/k>
Dec 21 21:30:02 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:30:02+08:00" level=info msg="Waiting to retrieve agent configuration; server>
Dec 21 21:30:02 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:30:02+08:00" level=info msg="Tunnel server egress proxy waiting for runtime >
Dec 21 21:30:07 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:30:07+08:00" level=error msg="unable to read node password file: open /etc/k>
Dec 21 21:30:07 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:30:07+08:00" level=info msg="Waiting to retrieve agent configuration; server>
Dec 21 21:30:07 weiban-prod-k8e-master-02 k8e[2955]: time="2022-12-21T21:30:07+08:00" level=info msg="Tunnel server egress proxy waiting for runtime >
lines 1-24/24 (END)`

**Comment by xiaods** [comment]
好像是读不到本地的password文件，请帮我提供点完整日志。
```
journalctl -u k8e -n 1000 > k8e.log
```

**Comment by xiaods** [comment]
fixed.

**Comment by xiaods** [comment]
@snakeliwei  please follow https://getk8e.com/docs/install/200-quick-start/ to add second master, it works like a charm.

**Comment by xiaods** [comment]
close as resolved
