### ISSUE TITLE
如何生成不同ip的kubeconfig 证书

### ISSUE THREAD

**Issue by defp** [xiaods/k8e#303]
原先是 kubeconfig server是内网的ip
比如     server: https://10.3.56.131:6443

如果我想签发一个新的公网ip的，用什么命令？

**Comment by xiaods** [comment]
> 原先是 kubeconfig server是内网的ip 比如 server: https://10.3.56.131:6443
> 
> 如果我想签发一个新的公网ip的，用什么命令？

你是想给一个user发一个kubeconfig文件，方便他远程来管理对吧。

**Comment by xiaods** [comment]
我记得复制一份kubeconfig，然后改一下ip就可以访问了。

Note : 对于 k8s 高可用集群场景下，一般我们会使用VIP访问kube-api-server，这里需要注意：因为k8e是默认自动生成TLS证书并在6443端口上提供TLS支持，如果想让外部正常通过VIP端口访问内部k8s集群的6443端口，我们就需要把VIP地址也添加到TLS证书中。TLS SAN配置如下：

```bash
# --tls-san value   (listener) Add additional hostname or IP as a Subject Alternative Name in the TLS cert
# bootstrap server和其它server都需要配置如下参数：
curl -sfL https://getk8e.com/install.sh | INSTALL_K8E_EXEC="--tls-san <这里可以加一下公网ip，例如114.114.114.114>" sh -
```

**Comment by defp** [comment]
```
E0222 15:34:44.474701 26939 proxy_server.go:147] Error while proxying request: x509: certificate is valid for 10.3.56.131, 10.3.56.132, 10.3.56.133, 10.3.56.135, 10.43.0.1, 127.0.0.1, ::1, not 218.108.x.x
```
直接换ip不行，可能之前没加TLS SAN配置

**Comment by xiaods** [comment]
> TLS SAN

手工在第一台master节点，编辑/etc/systemd/system/k8e.service
手工加一下--tls-san，例子：
```bash
ExecStart=/usr/local/bin/k8e \
    server \
        '--cluster-init' \
        '--tls-san' \
        '11.11.11.11' \
        '--tls-san' \
        '12.12.12.12' \
```

然后systemctl restart k8e，应该就可以了

**Comment by xiaods** [comment]
SAN应该根据客户要求的SNI主机名，按需添加到动态监听器cert中。试着在master服务器上运行以下程序。
```
curl -vk --resolve 172.31.13.97:6443:127.0.0.1  https://172.31.13.97:6443/ping
```

**Comment by xiaods** [comment]
@defp any update?

**Comment by defp** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/612381/220856795-3645a6dd-5f6d-4cb8-99f4-42b96e5823f4.png">

不太行
<img width="1802" alt="image" src="https://user-images.githubusercontent.com/612381/220857488-02462f4c-bac6-4e9b-926b-cc4b959bd166.png">

**Comment by xiaods** [comment]
<img width="716" alt="截屏2023-02-23 下午11 58 58" src="https://user-images.githubusercontent.com/37678/220961538-b665a596-a835-4143-8622-d962ed406e53.png">

<img width="728" alt="截屏2023-02-23 下午11 59 29" src="https://user-images.githubusercontent.com/37678/220961687-ca5791ee-9d4c-4a40-98a4-e837ac5c2d81.png">

<img width="720" alt="截屏2023-02-24 上午12 00 06" src="https://user-images.githubusercontent.com/37678/220961871-140c49ec-017a-4f87-8877-61a7a2178d2a.png">

<img width="716" alt="截屏2023-02-24 上午12 00 30" src="https://user-images.githubusercontent.com/37678/220961969-ad40ac22-a979-46b6-b613-7afeb43e7d5a.png">

操作顺序：
我在AWS上启动一台机器，然后执行安装单机版k8e。启动后，把远程的kubeconfig文件 /etc/k8e/k8s.yaml文件复制到本地。编辑文件把地址改为公网地址。然后在AWS上把6443端口打开，就可以访问了。

之后，我在k8e.service添加tls-san 公网地址，重启后，查看日志，已经自动加上了。仅供参考。如果你能提供测试方法，我乐意帮你在测试一遍。

**Comment by defp** [comment]
我临时用 ssh forward的方式
	LocalForward 127.0.0.1:6444 10.3.56.131:6443 
	
我搜到了这个方案，https://github.com/k3s-io/k3s/issues/1381#issuecomment-1220219450
不知道会不会影响原来的kubeconfig文件

**Comment by xiaods** [comment]
> 我临时用 ssh forward的方式 LocalForward 127.0.0.1:6444 10.3.56.131:6443
> 
> 我搜到了这个方案，[k3s-io/k3s#1381 (comment)](https://github.com/k3s-io/k3s/issues/1381#issuecomment-1220219450) 不知道会不会影响原来的kubeconfig文件

不会影响的。我这边啥都不用改，直接可以操作
